### ISSUE TITLE
person_id issue

### ISSUE THREAD

**Issue by kulinba** [DataAcademy/konfliktinteresa#3]
**Person_id** are different in these two csv files located on the rep **raw** https://github.com/DataAcademy/konfliktinteresa/tree/master/data/raw. When we re-run the script for **job.csv** to see what are real ID numbers we got completely different id numbers from these two appearing in **company-ownership.csv** and **job.csv**. Petar and I are not sure why is this happening but this will prevent us from merging these two tables at one point.

**Comment by mihi-tr** [comment]
Are both these files generated from the same database? If yes they _should_ have the same IDs per name. Otherwise we have to check the SQL statements to see whether they make sense.
